services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: appdb
    ports: ["5432:5432"]
    volumes:
      - pg:/var/lib/postgresql/data
volumes:
  pg: {}
